language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IpzQmSYEKNxHJ7qwB4N2SmZhXXZs3LDu01diA05y09xbPM84mFY2ZV6946GcXBXttDevwmQo8j8LauFkWlwPPSTVICtDLO6luRA9aKsWC9Oc/GxNTS0c2SuZREqDw51xMdq+G71E3ESFp9T2BfitQrKL38ydcJD739GBXlMSbI9BFwvD95ZBg6ZxM56wjZZ8aysT0Rtsvij9HOHxfOUFuiI5XCzE3ZVLWXCSbAyyIw97WcrXARcHjRH2uHnzjlZbz5DwjQ+c8Lj8riX+X1MSh+bN5x1mUKeujYcfq3YpTAk/os6ErgkSKnGWXvyDgY4hZksJZqP+ixyRltuvsgY3/p0RAyM+bzlLRrtyM/c1yHbYUM6eo4MiZWAF2pv6gXyGP9aomGDHWQGa9Yme9uZUh9dhhbfygvj4Z6Wotm+y0aqTtkMrG5iQcmPuVrshingsdhJKDkpSWQjtzkU+8DAb89kUb/hjK+DQJK4fPh+p6X2z+D+v/okNmnNvFT7Phe0vCuqrMyGFgvj9Sq1iowoxUZCA8WjdBAFkLOWo4pa07JDDKB04uOq5DiY6eT/upVjY5BFjtz3sPrmeoWH/RmapVtXGTJUiS4jIxiH2esmTJ7jHhVLnTciwkpOBMdheloTC260DmiSzHbJ4tThsoD5qFjYRkcbIaGxlGYoNQiKKt/4="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "KeepCryingEngine/KeepCryingEngine"
    notification_email: pere.viader22@gmail.com
    branch_pattern: coverity_scan
